In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("../data/weather_data.csv")

In [11]:
df.head()

   YEAR  MO  DY  HR   T2M   RH2M     PS
0  2023   1   1   0  7.60  66.63  99.51
1  2023   1   1   1  7.01  68.41  99.49
2  2023   1   1   2  6.95  68.69  99.49
3  2023   1   1   3  6.31  70.77  99.46
4  2023   1   1   4  6.12  71.02  99.45

In [12]:
df.shape

(31920, 7)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31920 entries, 0 to 31919
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YEAR    31920 non-null  int64
 1   MO      31920 non-null  int64
 2   DY      31920 non-null  int64
 3   HR      31920 non-null  int64
 4   T2M     31920 non-null  float64
 5   RH2M    31920 non-null  float64
 6   PS      31920 non-null  float64
dtypes: float64(3), int64(4)
memory usage: 1.7 MB

In [14]:
df.describe()

,YEAR,MO,DY,HR,T2M,RH2M,PS
count,31920.000000,31920.000000,31920.000000,31920.000000,31920.000000,31920.000000,31920.000000
mean,2024.351880,6.147368,15.651128,11.500000,23.075257,49.483644,95.947774
std,1.062472,3.367200,8.777592,6.922295,49.399952,55.639912,52.067079
min,2023.000000,1.000000,1.000000,0.000000,-999.000000,-999.000000,-999.000000
25%,2023.000000,3.000000,8.000000,5.750000,19.030000,31.447500,97.830000
50%,2024.000000,6.000000,16.000000,11.500000,26.450000,50.180000,98.400000
75%,2025.000000,9.000000,23.000000,17.250000,31.502500,70.720000,99.030000
max,2026.000000,12.000000,31.000000,23.000000,48.500000,100.000000,100.130000

In [15]:
df.isnull().sum()

YEAR    0
MO      0
DY      0
HR      0
T2M     0
RH2M    0
PS      0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)