In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = pd.read_csv(
    "../data/weather_cleaned.csv",
    parse_dates=['datetime']
)

In [17]:
df

         T2M   RH2M     PS            datetime
0       7.60  66.63  995.1 2023-01-01 00:00:00
1       7.01  68.41  994.9 2023-01-01 01:00:00
2       6.95  68.69  994.9 2023-01-01 02:00:00
3       6.31  70.77  994.6 2023-01-01 03:00:00
4       6.12  71.02  994.5 2023-01-01 04:00:00
...      ...    ...    ...                 ...
31843  29.16  85.16  979.3 2026-08-19 19:00:00
31844  28.72  87.20  979.8 2026-08-19 20:00:00
31845  28.35  88.36  980.0 2026-08-19 21:00:00
31846  27.96  89.88  979.8 2026-08-19 22:00:00
31847  27.52  91.83  979.7 2026-08-19 23:00:00

[31848 rows x 4 columns]

In [18]:
df['hour'] = df['datetime'].dt.hour
df['month'] = df['datetime'].dt.month

In [21]:
df['T2M_diff'] = df['T2M'].diff()
df['RH2M_diff'] = df['RH2M'].diff()
df['PS_diff'] = df['PS'].diff()

In [23]:
df['T2M_roll_mean'] = df['T2M'].rolling(24).mean()
df['RH2M_roll_mean'] = df['RH2M'].rolling(24).mean()
df['PS_roll_mean'] = df['PS'].rolling(24).mean()

In [26]:
df['T2M_roll_std'] = df['T2M'].rolling(24).std()
df['RH2M_roll_std'] = df['RH2M'].rolling(24).std()
df['PS_roll_std'] = df['PS'].rolling(24).std()

In [29]:
df.head(30)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31848 entries, 0 to 31847
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   T2M             31848 non-null  float64
 1   RH2M            31848 non-null  float64
 2   PS              31848 non-null  float64
 3   datetime        31848 non-null  datetime64[ns]
 4   hour            31848 non-null  int32
 5   month           31848 non-null  int32
 6   T2M_diff        31847 non-null  float64
 7   RH2M_diff       31847 non-null  float64
 8   PS_diff         31847 non-null  float64
 9   T2M_roll_mean   31825 non-null  float64
 10  RH2M_roll_mean  31825 non-null  float64
 11  PS_roll_mean    31825 non-null  float64
 12  T2M_roll_std    31825 non-null  float64
 13  RH2M_roll_std   31825 non-null  float64
 14  PS_roll_std     31825 non-null  float64
dtypes: datetime64[ns](1), float64(12), int32(2)
memory usage: 3.4 MB

,T2M,RH2M,PS,datetime,hour,month,T2M_diff,RH2M_diff,PS_diff,T2M_roll_mean,RH2M_roll_mean,PS_roll_mean,T2M_roll_std,RH2M_roll_std,PS_roll_std
count,31848.000000,31848.000000,31848.000000,31848,31848.000000,31848.00000,31847.000000,31847.000000,31847.000000,31825.000000,31825.000000,31825.000000,31825.000000,31825.000000,31825.000000
mean,25.385901,51.853992,984.231647,2024-10-25 11:30:00,11.500000,6.14318,0.000625,0.000791,-0.000484,25.389469,51.842065,984.229351,4.655932,12.839435,1.231467
min,0.450000,3.090000,966.700000,2023-01-01 00:00:00,0.000000,1.00000,-6.190000,-27.220000,-2.000000,7.762500,6.908750,968.787500,0.703350,1.615056,0.423217
25%,19.090000,31.597500,978.300000,2023-11-28 17:45:00,5.750000,3.00000,-0.780000,-1.450000,-0.300000,18.863750,35.860833,978.241667,3.459921,10.428706,1.024262
50%,26.470000,50.260000,984.000000,2024-10-25 11:30:00,11.500000,6.00000,-0.360000,0.690000,0.000000,26.902500,48.945000,983.925000,4.876649,12.722645,1.185778
75%,31.520000,70.770000,990.300000,2025-09-22 05:15:00,17.250000,9.00000,0.630000,2.100000,0.400000,30.773750,70.153333,990.354167,5.793749,15.023038,1.394080
max,48.500000,100.000000,1001.300000,2026-08-19 23:00:00,23.000000,12.00000,6.290000,23.070000,2.400000,41.438750,95.778750,999.387500,8.265422,31.519926,3.217274
std,8.877278,24.735230,6.880998,NaN,6.922295,3.36985,1.514294,4.577009,0.508407,7.478312,20.965794,6.766534,1.470200,3.861939,0.300581

In [30]:
df['T2M_roll_dev'] = df['T2M'] - df['T2M_roll_mean']
df['RH2M_roll_dev'] = df['RH2M'] - df['RH2M_roll_mean']
df['PS_roll_dev'] = df['PS'] - df['PS_roll_mean']

In [31]:
df = df.dropna().reset_index(drop=True)

In [33]:
print(df.describe())
df.head()

                T2M          RH2M            PS             datetime  \
count  31825.000000  31825.000000  31825.000000                31825
mean      25.394887     51.855372    984.223268  2024-10-25 23:00:00
min        0.450000      3.090000    966.700000  2023-01-01 23:00:00
25%       19.100000     31.590000    978.300000  2023-11-29 11:00:00
50%       26.480000     50.260000    984.000000  2024-10-25 23:00:00
75%       31.520000     70.770000    990.300000  2025-09-22 11:00:00
max       48.500000    100.000000   1001.300000  2026-08-19 23:00:00
std        8.873161     24.740895      6.876376                  NaN

               hour         month      T2M_diff     RH2M_diff       PS_diff  \
count  31825.000000  31825.000000  31825.000000  31825.000000  31825.000000
mean      11.500361      6.146897      0.000470      0.001440     -0.000534
min        0.000000      1.000000     -6.190000    -27.220000     -2.000000
25%        6.000000      3.000000     -0.780000     -1.450000     -0.300000
50%       12.000000      6.000000     -0.360000      0.690000      0.000000
75%       18.000000      9.000000      0.630000      2.100000      0.400000
max       23.000000     12.000000      6.290000     23.070000      2.400000
std        6.922487      3.368229      1.514329      4.577119      0.508459

       T2M_roll_mean  RH2M_roll_mean  PS_roll_mean  T2M_roll_std  \
count   31825.000000    31825.000000  31825.000000  31825.000000
mean       25.389469       51.842065    984.229351      4.655932
min         7.762500        6.908750    968.787500      0.703350
25%        18.863750       35.860833    978.241667      3.459921
50%        26.902500       48.945000    983.925000      4.876649
75%        30.773750       70.153333    990.354167      5.793749
max        41.438750       95.778750    999.387500      8.265422
std         7.478312       20.965794      6.766534      1.470200

       RH2M_roll_std   PS_roll_std  T2M_roll_dev  RH2M_roll_dev   PS_roll_dev
count   31825.000000  31825.000000  31825.000000   31825.000000  31825.000000
mean       12.839435      1.231467      0.005418       0.013306     -0.006083
min         1.615056      0.423217    -11.505833     -52.000833     -5.141667
25%        10.428706      1.024262     -3.732083     -10.475417     -0.958333
50%        12.722645      1.185778     -0.926250       1.658750     -0.037500
75%        15.023038      1.394080      3.790417      10.334583      0.920833
max        31.519926      3.217274     13.371667      49.181667      5.700000
std         3.861939      0.300581      4.828105      13.626691      1.392882

,T2M,RH2M,PS,datetime,hour,month,T2M_diff,RH2M_diff,PS_diff,T2M_roll_mean,RH2M_roll_mean,PS_roll_mean,T2M_roll_std,RH2M_roll_std,PS_roll_std,T2M_roll_dev,RH2M_roll_dev,PS_roll_dev
0,11.78,48.78,996.7,2023-01-01 23:00:00,23,1,-0.78,2.77,0.0,12.904167,49.895833,995.862500,5.030627,14.846591,0.920214,-1.124167,-1.115833,0.837500
1,10.41,54.30,996.5,2023-01-02 00:00:00,0,1,-1.37,5.52,-0.2,13.021250,49.382083,995.920833,4.933574,14.450394,0.914130,-2.611250,4.917917,0.579167
2,9.59,58.03,996.3,2023-01-02 01:00:00,1,1,-0.82,3.73,-0.2,13.128750,48.949583,995.979167,4.823784,14.004587,0.890520,-3.538750,9.080417,0.320833
3,9.07,60.90,995.9,2023-01-02 02:00:00,2,1,-0.52,2.87,-0.4,13.217083,48.625000,996.020833,4.724100,13.611943,0.860727,-4.147083,12.275000,-0.120833
4,8.54,63.80,995.4,2023-01-02 03:00:00,3,1,-0.53,2.90,-0.5,13.310000,48.334583,996.054167,4.602711,13.186637,0.817727,-4.770000,15.465417,-0.654167

In [34]:
df.to_csv("../data/weather_features.csv", index=False)